### ISSUE TITLE
运行代码报错

### ISSUE THREAD

**Issue by 10086e** [OpenEthan/SMSBoom#139]
python smsboom.py
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/SMSBoom/smsboom.py", line 5, in <module>
    from utils.log import logger
  File "/data/data/com.termux/files/home/SMSBoom/utils/log.py", line 3, in <module>
    from loguru import logger
ModuleNotFoundError: No module named 'loguru'

**Comment by WhaleFell** [comment]
请 pip 安装 loguru 模块，`pip3 install loguru` 如果还出现 `ModuleNotFoundError` 的错误，请尝试 `pip3 install -r requiments.txt` 安装依赖库。

**Comment by lingzhuxin** [comment]
> 请 pip 安装 loguru 模块，`pip3 install loguru` 如果还出现 `ModuleNotFoundError` 的错误，请尝试 `pip3 install -r requiments.txt` 安装依赖库。

这个要求英文打错了，但是我用正确的也安装不成功啊，哈哈哈
