### ISSUE TITLE
Json file syntax error:Expecting ',' delimiter: line 102 column 78 (char 12304) 

### ISSUE THREAD

**Issue by 1139430086** [OpenEthan/SMSBoom#193]
✔️  14:47:58,300 [Traceback (most recent call last):
SUCCESS  File "C:\Users\11394\Desktop\django\SMSBoom-master\smsboom.py", line 91, in load_getapi
]     datas = json.loads(j.read())
  File "C:\Users\11394\AppData\Local\Programs\Python\Python39\lib\json\__init__.py", line 346, in loads
MainThread    return _default_decoder.decode(s)
   File "C:\Users\11394\AppData\Local\Programs\Python\Python39\lib\json\decoder.py", line 337, in decode
smsboom    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
:  File "C:\Users\11394\AppData\Local\Programs\Python\Python39\lib\json\decoder.py", line 353, in raw_decode
73    obj, end = self.scan_once(s, idx)
 - json.decoder.JSONDecodeError: Expecting ',' delimiter: line 102 column 78 (char 12304)

During handling of the above exception, another exception occurred:

api.json 加载完成 接口数:3Traceback (most recent call last):

  File "C:\Users\11394\Desktop\django\SMSBoom-master\smsboom.py", line 205, in <module>
❌      cli()
14:47:58,301  File "C:\Users\11394\AppData\Local\Programs\Python\Python39\lib\site-packages\click\core.py", line 1128, in __call__
 [ERROR]     return self.main(*args, **kwargs)
MainThread  File "C:\Users\11394\AppData\Local\Programs\Python\Python39\lib\site-packages\click\core.py", line 1053, in main
 smsboom    rv = self.invoke(ctx)
:  File "C:\Users\11394\AppData\Local\Programs\Python\Python39\lib\site-packages\click\core.py", line 1659, in invoke
95 -     return _process_result(sub_ctx.command.invoke(sub_ctx))
Json file syntax error:Expecting ',' delimiter: line 102 column 78 (char 12304)  File "C:\Users\11394\AppData\Local\Programs\Python\Python39\lib\site-packages\click\core.py", line 1395, in invoke

    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\11394\AppData\Local\Programs\Python\Python39\lib\site-packages\click\core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\11394\Desktop\django\SMSBoom-master\smsboom.py", line 160, in oneRun
    _api_get = load_getapi()
  File "C:\Users\11394\Desktop\django\SMSBoom-master\smsboom.py", line 96, in load_getapi
    raise ValueError
ValueError

**Comment by qiujiaweialex** [comment]
大大们解答一下
