### ISSUE TITLE
Error,Please help me take a look（./smsboom.exe asyncrun --p 155#######）

### ISSUE THREAD

**Issue by qiangli5272** [OpenEthan/SMSBoom#339]
Traceback (most recent call last):
❌    File "smsboom.py", line 68, in load_json
15:20:00,222  File "json\__init__.py", line 357, in loads
 [  File "json\decoder.py", line 337, in decode
  File "json\decoder.py", line 355, in raw_decode
ERRORjson.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
]
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "smsboom.py", line 205, in <module>
MainThread  File "click\core.py", line 1130, in __call__
   File "click\core.py", line 1055, in main
smsboom  File "click\core.py", line 1657, in invoke
:  File "click\core.py", line 1404, in invoke
76  File "click\core.py", line 760, in invoke
 -   File "smsboom.py", line 146, in asyncRun
Json file syntax error:Expecting value: line 1 column 1 (char 0)  File "smsboom.py", line 77, in load_json

ValueError
[5548] Failed to execute script 'smsboom' due to unhandled exception!

**Comment by lynx14235** [comment]
asyncrun用了之后就发了5条信息，我已经更新过接口了，是不是api接口大多失效了
